server:
    port: ${PORT}

spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${USERNAME}
        password: ${PASSWORD}
        testedWhileIdle: true
        timeBetweenEvictionRunMillis: 3600000
        validationQuery: SELECT 1
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB

poetical:
    username: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}
    resource-id: ${RESOURCE_ID}

---
   
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/poeticaltestdb
        username: root
        password:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB

server:
    port: 9090

poetical:
    username: admin
    password: _pass
    resource-id: _pass_admin_server
