server:
    port: 9090

spring:
    datasource:
        url: ${CUSTOM_DB}
        driverClassName: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB

poetical:
    username: ${ADMIN_ID}
    password: ${PASS_CODE}
    resource-id: ${RESOURCE_ID}
    
