server:
    port: 9090

spring:
    datasource:
        url: jdbc:mysql://localhost/id7748605_poeticaldb
        username: id7748605_poetical_admin
        password: poeticalissecret
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB

poetical:
    username: poetical_admin
    password: poetical_secret
    resource-id: poetical2018asresource
    
