server:
    port: ${PORT}

spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${USERNAME}
        password: ${PASSWORD}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB

poetical:
    username: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}
    resource-id: ${RESOURCE_ID}
    
